version: "3"

services:
  apache:
    container_name: sklep_apache
    build: ./apache
    ports:
      - 80:80
      - 443:443
# info - czy to ponizej jest potrzebne, by działało powiązanie między php-fpm a apache ???
    links:
      - php
    networks:
      - backend
# info ends
    volumes:
      - .:/app

  php:
    container_name: sklep_php
    build: ./php
    ports:
      - 9000:9000
# info - czy to ponizej jest potrzebne, by działało powiązanie między php-fpm a apache ???
    networks:
      - backend
# info ends
    volumes:
      - .:/app

networks:
  backend: